name: Check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      actions: read
    steps:
      - name: Make temporary bin dir
        id: temp-bin-dir
        run: |
          mkdir $RUNNER_TEMP/bin
          echo "path=$RUNNER_TEMP/bin" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Mise
        uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          install: true
          cache: true

      - name: Install Dependencies
        run: |
          flutter pub get
          cd example
          flutter pub get

      - name: Dart Analyzer
        uses: invertase/github-action-dart-analyzer@e981b01a458d0bab71ee5da182e5b26687b7101b # v3.0.0
        with:
          fatal-infos: true

      - name: Test
        run: flutter test --coverage

      - name: Octocov
        uses: k1LoW/octocov-action@73d561f65d59e66899ed5c87e4621a913b5d5c20 # v1.5.0
        with:
          install-dir: ${{ steps.temp-bin-dir.outputs.path }}
